[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.3"

[prune]
  go-tests = true
  unused-packages = true
